### ISSUE TITLE
Bug related to worker names

### ISSUE THREAD

**Issue by ocaisa** [E-CAM/jobqueue_features#42]
The names given in job scripts are not unique so they seem to be causing problems, take the job script
```
#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -p devel
#SBATCH -n 48
#SBATCH --cpus-per-task=1
#SBATCH --mem=117G
#SBATCH -t 00:05:00
#SBATCH --ntasks-per-node=24
#SBATCH --nodes=2
module --force purge
module use /usr/local/software/jureca/OtherStages
module load Stages/Devel-2019a
module load Intel
module load dask
module load jobqueue_features
/usr/local/software/jureca/Stages/Devel-2019a/software/Python/3.6.8-GCCcore-8.3.0/bin/python -m distributed.cli.dask_worker tcp://10.80.32.31:33836 --nthreads 1 --memory-limit 125.00GB --name GROMACS_cluster --nanny --death-timeout 15 --local-directory /tmp --interface ib0

```
Note that we have `--name GROMACS_cluster` there, but I'm pretty sure that this is meant to be a unique name. When run with more than 1 worker this leads to an error
```
       Preparing the environment for use of requested stage ( Devel-2019a ).
     
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.80.33.42:43473'
distributed.worker - INFO -       Start worker at:    tcp://10.80.33.42:39154
distributed.worker - INFO -          Listening to:    tcp://10.80.33.42:39154
distributed.worker - INFO - Waiting to connect to:    tcp://10.80.32.31:46272
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  125.00 GB
distributed.worker - INFO -       Local Directory:       /tmp/worker-3qg6tnbr
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Stopping worker at tcp://10.80.33.42:39154
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/dask/2.13.0-GCCcore-8.3.0/lib/python3.6/site-packages/distributed/node.py", line 176, in wait_for
    await asyncio.wait_for(future, timeout=timeout)
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/dask/2.13.0-GCCcore-8.3.0/lib/python3.6/site-packages/distributed/worker.py", line 1060, in start
    await self._register_with_scheduler()
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/dask/2.13.0-GCCcore-8.3.0/lib/python3.6/site-packages/distributed/worker.py", line 860, in _register_with_scheduler
    raise ValueError("Unexpected response from register: %r" % (response,))
ValueError: Unexpected response from register: {'status': 'error', 'message': 'name taken, GROMACS_cluster', 'time': 1585323929.0770907}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/dask/2.13.0-GCCcore-8.3.0/lib/python3.6/site-packages/distributed/nanny.py", line 713, in run
    await worker
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/dask/2.13.0-GCCcore-8.3.0/lib/python3.6/site-packages/distributed/node.py", line 181, in wait_for
    type(self).__name__, timeout
concurrent.futures._base.TimeoutError: Worker failed to start in 15 seconds
distributed.nanny - ERROR - Failed while trying to start worker process: Worker failed to start in 15 seconds
distributed.nanny - INFO - Closing Nanny at 'tcp://10.80.33.42:43473'
distributed.dask_worker - INFO - End worker
```
Note the true error inside there:
```
raise ValueError("Unexpected response from register: %r" % (response,))
ValueError: Unexpected response from register: {'status': 'error', 'message': 'name taken, GROMACS_cluster', 'time': 1585323929.0770907}
```

This may be related to https://github.com/dask/dask-jobqueue/pull/396

**Comment by ocaisa** [comment]
I think the problem is https://github.com/E-CAM/jobqueue_features/blob/master/jobqueue_features/clusters.py#L598 , I don't think we are meant to override that `name`, that should be set by the cluster...do you remember why you had to do that?

**Comment by ocaisa** [comment]
There's something wrong here, there's no way you can know the jobid when you submit the job so that name not being unique should not be a problem. Let me double check the issue and make sure I am not doing something stupid

**Comment by ocaisa** [comment]
I think this is not actually a problem from our end, I updated to the latest Dask on JURECA and I'm not seeing this right now. I am seeing the adaptive scaling being very aggressive in starting and stopping workers though, investigating that now.

**Comment by ocaisa** [comment]
Urgh, we are back to the situation where functions are being evaluated as `pure`, but I don't know why.

**Comment by ocaisa** [comment]
Ok, this really exists. Once we scale beyond a single worker we are getting the error that started this issue  (at least on JURECA). Still do not know why it happens though.

**Comment by ocaisa** [comment]
You can reproduce this with
```
from __future__ import print_function
import os
import sys
import pprint
import time

import numpy as np

from jobqueue_features.clusters import CustomSLURMCluster
from jobqueue_features.decorators import on_cluster, mpi_task
from jobqueue_features.mpi_wrapper import mpi_wrap
from jobqueue_features.functions import set_default_cluster
from jobqueue_features.mpi_wrapper import SRUN

import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)

import dask.config


GROMACS_cluster = CustomSLURMCluster(
    name="HSW_cluster",
    walltime="00:05:00",
    queue="devel",
    interface="ib0",
    nodes=2,
    mpi_launcher=SRUN,
    nanny=False,
    mpi_mode=True,
    fork_mpi=True,
    maximum_scale=2,
    scale=2,
)

@on_cluster(cluster=GROMACS_cluster)
@mpi_task(cluster_id=GROMACS_cluster.name)
def run_mpi(x=None, **kwargs):
    script_path = os.path.join(
        os.path.dirname(__file__), "resources", "helloworld2.py"
    )
    t = mpi_wrap(
        pre_launcher_opts='time -f "%e"',
        executable="python",
        exec_args="{} {} ".format(script_path, x),
        **kwargs
    )
    return t

def main():
    pprint.pprint(dask.config.config)
    t = []

    if len(sys.argv) == 2:
        n_samples = int(sys.argv[1])
    else:
        n_samples = 50
    for x in range(n_samples):
        t.append(run_mpi(x=x))
    pprint.pprint([i.result() for i in t])
    runtimes = [float((i.result()["err"]).split(b"\n")[-2]) for i in t]
    print(
        "Cluster Compute Total (",
        len(runtimes),
        " samples)",
        sum(runtimes),
        " : Average ",
        np.mean(runtimes),
        " +/- ",
        np.var(runtimes),
    )

if __name__ == "__main__":
    main()
```
if you run this from the `examples` directory (and have everything loaded) with `python hsw_text.py 10` you should see the exception text in the job output

**Comment by ocaisa** [comment]
I wrote a simple test to check this behaviour in jobqueue:
```
from dask.distributed import Client
from dask_jobqueue import SLURMCluster
import dask.array as da
import numpy as np
import os
from time import time, sleep

import logging

logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)


def calc_pi_mc(size_in_bytes, chunksize_in_bytes=200e6):
    """Calculate PI using a Monte Carlo estimate."""
    
    size = int(size_in_bytes / 8)
    chunksize = int(chunksize_in_bytes / 8)
    
    xy = da.random.uniform(0, 1,
                           size=(size / 2, 2),
                           chunks=(chunksize / 2, 2))
    
    in_circle = ((xy ** 2).sum(axis=-1) < 1)
    pi = 4 * in_circle.mean()

    return pi

def print_pi_stats(size, pi, time_delta, num_workers):
    """Print pi, calculate offset from true value, and print some stats."""
    print(f"{size / 1e9} GB\n"
          f"\tMC pi: {pi : 13.11f}"
          f"\tErr: {abs(pi - np.pi) : 10.3e}\n"
          f"\tWorkers: {num_workers}"
          f"\t\tTime: {time_delta : 7.3f}s")

cluster = SLURMCluster(
    cores=24,
    processes=2,
    memory="100GB",
    shebang='#!/usr/bin/env bash',
    queue="batch",
    walltime="00:30:00",
    local_directory='/tmp',
    death_timeout="15s",
#    interface="ib0",
    log_directory=f'{os.environ["SCRATCH_cecam"]}/{os.environ["USER"]}/dask_jobqueue_logs/',
    project="ecam")

print(cluster.job_script())

cluster.adapt(minimum_jobs=2)

for size in (1e9 * n for n in (1, 10, 100)):
    
    start = time()
    pi = calc_pi_mc(size).compute()
    elaps = time() - start

    print_pi_stats(size, pi, time_delta=elaps,
                   num_workers=len(cluster.scheduler.workers))
```
If you run this you can see the `name` in the job scripts are simple numbers, so I think we need to revert #32

**Comment by AdamWlodarczyk** [comment]
I am very lost in that... I remember that there was a justification of that change so the dummy job gets the cluster name. But if this works without that change then it's all good.

**Comment by ocaisa** [comment]
The problem with `name` is that the job names that should be used from our yaml file are not getting picked up. You can see that already in the job scripts, so we should be able to add a test for that.

**Comment by ocaisa** [comment]
I took a look in jobqueue https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L177

We should be used `job_name` when we parse the name from the yaml file
